version: "3"

services:
    authtsapiapp:
        container_name: authtsapi-app
        restart: always
        build: .
        ports:
            - "5000:4000"
        links:
            - authtsapidb
        volumes:
            - .:/app/auth-ts-api
    authtsapidb:
        container_name: authtsapi-db
        image: mongo
        ports:
            - "27018:27017"
        logging:
            driver: none
